#
# Phalcon 4 + PHP 7.3 + Codeception
#

# Pull base image
FROM ruudboon/phalcon-php-cli:latest

RUN curl -LsS https://codeception.com/codecept.phar -o /usr/local/bin/codecept
RUN chmod a+x /usr/local/bin/codecept
